Add PR template
Otus-DevOps-2018-02/ifqthenp_infra pull request #1
Opened 2018-03-05 05:47 UTC by ifqthenp

Template for pull requests description has been added.

2018-03-05 16:55 UTC, ifqthenp commented
# Выполнено ДЗ № 02a

 - [x] Основное ДЗ

## В процессе сделано:
- Added template for pull requests description

## PR checklisk
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-03-10 05:05 UTC, ifqthenp commented
## The following tasks have been completed:

- Translated pull request template to English

2018-03-12 19:36 UTC, vitkhab requested changes
Все выполнено классно! Все четко и хорошо.

Для зачета прошу перенести описание PR в описание PR (в самый верхний пост PR, отредактировав его).
В рамках курса, описание должно содержать текущее состояние PR, а в комментариях ведется общение.

2018-03-14 12:49 UTC, vitkhab approved these changes
Все классно! Можно мерджить

2018-03-14 15:43 UTC, merged